name: tools
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray==0.11.3
  - iris==2.2
  - jupyter=1.0
  - matplotlib=3.0.3
  - netcdf4
  - ipywidgets
  - bokeh
  - holoviews
  - geoviews
  - pyqt
  - nodejs
